site_name: generating_impact_summaries
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: generating_impact_summaries
      handlers:
        python:
          options:
            docstring_style: numpy